Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

  BRIDGE_ADAPTER = "Intel(R) Wi-Fi 6 AX201 160MHz"

  # ---------------- DB VM ----------------
  config.vm.define "db01" do |db01|
    db01.vm.box = "centos/stream9"
    db01.vm.hostname = "db01"
    db01.vm.boot_timeout = 600
    db01.vm.network "public_network", ip: "192.168.56.15", bridge: BRIDGE_ADAPTER
    db01.vm.provider "virtualbox" do |vb|
      vb.memory = 600
    end
  end

  # ---------------- Memcache VM ----------------
  config.vm.define "mc01" do |mc01|
    mc01.vm.box = "centos/stream9"
    mc01.vm.hostname = "mc01"
    mc01.vm.boot_timeout = 600
    mc01.vm.network "public_network", ip: "192.168.56.14", bridge: BRIDGE_ADAPTER
    mc01.vm.provider "virtualbox" do |vb|
      vb.memory = 600
    end
  end

  # ---------------- RabbitMQ VM ----------------
  config.vm.define "rmq01" do |rmq01|
    rmq01.vm.box = "centos/stream9"
    rmq01.vm.hostname = "rmq01"
    rmq01.vm.boot_timeout = 600
    rmq01.vm.network "public_network", ip: "192.168.56.13", bridge: BRIDGE_ADAPTER
    rmq01.vm.provider "virtualbox" do |vb|
      vb.memory = 600
    end
  end

  # ---------------- Tomcat VM ----------------
  config.vm.define "app01" do |app01|
    app01.vm.box = "centos/stream9"
    app01.vm.hostname = "app01"
    app01.vm.boot_timeout = 600
    app01.vm.network "public_network", ip: "192.168.56.12", bridge: BRIDGE_ADAPTER
    app01.vm.provider "virtualbox" do |vb|
      vb.memory = 800
    end
  end

  # ---------------- Nginx Web VM ----------------
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/jammy64"
    web01.vm.hostname = "web01"
    web01.vm.boot_timeout = 600

    # ONLY bridged network (so Chrome can access)
    web01.vm.network "public_network", ip: "192.168.56.11", bridge: BRIDGE_ADAPTER

    web01.vm.provider "virtualbox" do |vb|
      vb.memory = 800
    end
  end

end
